Support for directly pulling IIIF resources from content servers
vitrivr/vitrivr-ng pull request #84
Opened 2021-07-21 11:34 UTC by singaltanmay

# Description

Uses the IIIF `resourceUrl` metadata value in the `IIIF` domain to directly pull image resources from IIIF content servers. [OpenSeaDragon](https://openseadragon.github.io/) image viewer is used to provide an easy-to-use interface for the users.

IIIF support has not yet been merged into cineast (see https://github.com/vitrivr/cineast/pull/217) so in order to make use of these new features you would need to checkout a compatible version of Cineast from https://github.com/singaltanmay/cineast/tree/feature/IIIF_Presentation_API and run an IIIF extraction job

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have reviewed my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (wiki, README, Website)
- [ ] I have updated the pre-built binary on the release page (for major changes)

2021-08-17 14:14 UTC, silvanheller reviewed
This looks good to me, thanks for the work @singaltanmay! I'll rely on the verdict of @Spiess since I assume he'll be doing a full-stack test.

2021-08-17 15:13 UTC, Spiess approved these changes
I have tested the changes with extracted IIIF resources, regular locally hosted images, image sequences and videos.

Everything now works as expected. In my opinion these changes can be merged.
Great work!

2021-08-20 14:43 UTC, sauterl requested changes
Thanks for the PR! Overall, this looks very good. However, there are a few minor changes requried before we merge this.

Also, please remove the openseadragon images (`src/assets/`), they are loaded elsewhere

2021-08-25 11:34 UTC, singaltanmay commented on src/app/core/basics/resolver.service.ts
> +        const size = (height || width) ? (xWidth + ',' + yHeight) : (metadata.get('IIIF.size') || 'full')
Done

2021-08-25 11:34 UTC, singaltanmay commented on src/app/objectdetails/quick-viewer.component.ts
> +    const viewer = openseadragon({
Done

2021-08-25 11:35 UTC, singaltanmay commented
> Thanks for the PR! Overall, this looks very good. However, there are a few minor changes requried before we merge this.
> 
> Also, please remove the openseadragon images (`src/assets/`), they are loaded elsewhere

Deleting the openseadragon images folder led to the icons not loading so I have left them in for now. I have implemented the other chagnes that you requested

2021-08-28 08:45 UTC, sauterl approved these changes
Thank you for your work. Indeed, the assets have to stay.

2021-08-28 08:46 UTC, merged